[revset-aliases]
'closest_pushable(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'

[aliases]
tug = ["util", "exec", "--", "sh", "-c", """
if [ "x$1" = "x" ]; then
  jj bookmark move --from "closest_bookmark(@)" --to "closest_pushable(@)"
else
  jj bookmark move --to "closest_pushable(@)" "$@"
fi
""", ""]
ov = [ "log", "-r", "all()", "--no-pager", "-n10" ] 
ll = [ "log", "-r", "all()" ] 

[ui]
default-command = [ "log", "-n10", "--no-pager" ]

[git]
colocate = false
